
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqVB6RA0KlBhxBzw3Dtcr8SDl2TC2FDtU',
    authDomain: 'praktikum-mobileapp-7446f.firebaseapp.com',
    databaseURL: 'https://praktikum-mobileapp-7446f-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'praktikum-mobileapp-7446f',
    storageBucket: 'praktikum-mobileapp-7446f.firebasestorage.app',
    messagingSenderId: '913521382972',
    appId: '1:913521382972:web:2f307b1431ab4690e0d539'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIhwQPQJpKTZeI1eVL0Ic2sGQzaXRfkNc',
    appId: '1:913521382972:android:5b0868d6fe128328e0d539',
    messagingSenderId: '913521382972',
    projectId: 'praktikum-mobileapp-7446f',
    storageBucket: 'praktikum-mobileapp-7446f.firebasestorage.app'
  );
}
